package com.sanchez.sanchez.bullkeeper_kids.domain.models

/**
 * Server Event Type Enum
 */
enum class ServerEventTypeEnum {
    DELETE_ALL_SCHEDULED_BLOCK_EVENT,
    DELETE_SCHEDULED_BLOCK_EVENT,
    SCHEDULED_BLOCK_IMAGE_CHANGED_EVENT,
    SCHEDULED_BLOCK_SAVED_EVENT,
    SCHEDULED_BLOCK_STATUS_CHANGED_EVENT,
    APP_RULES_LIST_SAVED_EVENT,
    APP_RULES_SAVED_EVENT,
    ADD_PHONE_NUMBER_BLOCKED_EVENT,
    DELETE_ALL_PHONE_NUMBER_BLOCKED_EVENT,
    DELETE_PHONE_NUMBER_BLOCKED_EVENT,
    UNLINK_TERMINAL_EVENT,
    TERMINAL_BED_TIME_STATUS_CHANGED,
    TERMINAL_CAMERA_STATUS_CHANGED,
    TERMINAL_SCREEN_STATUS_CHANGED,
    TERMINAL_SETTINGS_STATUS_CHANGED,
    TERMINAL_PHONE_CALLS_STATUS_CHANGED,
    APP_DISABLED_STATUS_CHANGED,
    GEOFENCE_ADDED_EVENT,
    GEOFENCE_DELETED_EVENT,
    GEOFENCES_DELETED_EVENT,
    ALL_GEOFENCE_DELETED_EVENT,
    FUN_TIME_UPDATED_EVENT,
    FUN_TIME_DAY_SCHEDULED_UPDATED_EVENT,
    MESSAGE_SAVED_EVENT,
    ALL_CONVERSATION_DELETED_EVENT,
    ALL_MESSAGES_DELETED_EVENT,
    DELETED_MESSAGES_EVENT,
    SET_MESSAGES_AS_VIEWED_EVENT,
    CONTACT_DISABLED_EVENT,
    DEVICE_PHOTO_DISABLED_EVENT,
    GEOFENCE_STATUS_CHANGED_EVENT
}